import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import Board from '../components/Board'

export default function Home() {
  return (
    <div >
      <Head>
        <title>掲示板</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Board/>
      </Layout>
    </div>
  )
}
